[2024-10-15T23:12:49.067+0000] {taskinstance.py:1037} DEBUG - previous_execution_date was called
[2024-10-15T23:12:49.093+0000] {__init__.py:51} DEBUG - Loading core task runner: StandardTaskRunner
[2024-10-15T23:12:49.109+0000] {taskinstance.py:1037} DEBUG - previous_execution_date was called
[2024-10-15T23:12:49.116+0000] {base_task_runner.py:68} DEBUG - Planning to run as the  user
[2024-10-15T23:12:49.119+0000] {taskinstance.py:789} DEBUG - Refreshing TaskInstance <TaskInstance: run_dbt_models.model.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:12:44.688778+00:00 [queued]> from DB
[2024-10-15T23:12:49.145+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.model.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:12:44.688778+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, This task instance was the first task instance for its task.
[2024-10-15T23:12:49.156+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.model.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:12:44.688778+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2024-10-15T23:12:49.156+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.model.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:12:44.688778+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2024-10-15T23:12:49.157+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.model.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:12:44.688778+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-10-15T23:12:49.157+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_dbt_models.model.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:12:44.688778+00:00 [queued]>
[2024-10-15T23:12:49.159+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.model.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:12:44.688778+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, This task instance was the first task instance for its task.
[2024-10-15T23:12:49.165+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.model.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:12:44.688778+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2024-10-15T23:12:49.170+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.model.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:12:44.688778+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2024-10-15T23:12:49.170+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.model.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:12:44.688778+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-10-15T23:12:49.170+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_dbt_models.model.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:12:44.688778+00:00 [queued]>
[2024-10-15T23:12:49.171+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-10-15T23:12:49.183+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): model.dbt_btc_transform.stg_kaggle__btcusdt> on 2024-10-15 23:12:44.688778+00:00
[2024-10-15T23:12:49.186+0000] {standard_task_runner.py:57} INFO - Started process 822 to run task
[2024-10-15T23:12:49.190+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'run_dbt_models', 'model.dbt_btc_transform.stg_kaggle__btcusdt', 'manual__2024-10-15T23:12:44.688778+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/run_dbt_models.py', '--cfg-path', '/tmp/tmp4vn_2bgj']
[2024-10-15T23:12:49.191+0000] {standard_task_runner.py:85} INFO - Job 41: Subtask model.dbt_btc_transform.stg_kaggle__btcusdt
[2024-10-15T23:12:49.192+0000] {cli_action_loggers.py:65} DEBUG - Calling callbacks: [<function default_action_log at 0x7f7b0c199c10>]
[2024-10-15T23:12:49.245+0000] {taskinstance.py:1037} DEBUG - previous_execution_date was called
[2024-10-15T23:12:49.253+0000] {task_command.py:410} INFO - Running <TaskInstance: run_dbt_models.model.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:12:44.688778+00:00 [running]> on host d867809303f2
[2024-10-15T23:12:49.253+0000] {settings.py:353} DEBUG - Disposing DB connection pool (PID 822)
[2024-10-15T23:12:49.254+0000] {settings.py:212} DEBUG - Setting up DB connection pool (PID 822)
[2024-10-15T23:12:49.254+0000] {settings.py:285} DEBUG - settings.prepare_engine_args(): Using NullPool
[2024-10-15T23:12:49.256+0000] {taskinstance.py:789} DEBUG - Refreshing TaskInstance <TaskInstance: run_dbt_models.model.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:12:44.688778+00:00 [running]> from DB
[2024-10-15T23:12:49.299+0000] {taskinstance.py:1037} DEBUG - previous_execution_date was called
[2024-10-15T23:12:49.308+0000] {taskinstance.py:868} DEBUG - Clearing XCom data
[2024-10-15T23:12:49.340+0000] {retries.py:80} DEBUG - Running RenderedTaskInstanceFields._do_delete_old_records with retries. Try 1 of 3
[2024-10-15T23:12:49.355+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='airflow@example.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='run_dbt_models' AIRFLOW_CTX_TASK_ID='model.dbt_btc_transform.stg_kaggle__btcusdt' AIRFLOW_CTX_EXECUTION_DATE='2024-10-15T23:12:44.688778+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-15T23:12:44.688778+00:00'
[2024-10-15T23:12:49.355+0000] {__init__.py:117} DEBUG - Preparing lineage inlets and outlets
[2024-10-15T23:12:49.356+0000] {__init__.py:155} DEBUG - inlets: [], outlets: []
[2024-10-15T23:12:49.356+0000] {bash.py:186} DEBUG - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='airflow@example.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='run_dbt_models' AIRFLOW_CTX_TASK_ID='model.dbt_btc_transform.stg_kaggle__btcusdt' AIRFLOW_CTX_EXECUTION_DATE='2024-10-15T23:12:44.688778+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-15T23:12:44.688778+00:00'
[2024-10-15T23:12:49.357+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-10-15T23:12:49.357+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n            export DBT_SCHEMA=analytics &&\n            cd /opt/airflow/dbt &&\n            /home/airflow/.local/bin/dbt --no-write-json run --target dev --models stg_kaggle__btcusdt\n            ']
[2024-10-15T23:12:49.365+0000] {subprocess.py:86} INFO - Output:
[2024-10-15T23:12:51.835+0000] {subprocess.py:93} INFO - [0m23:12:51  Running with dbt=1.8.7
[2024-10-15T23:12:52.156+0000] {subprocess.py:93} INFO - [0m23:12:52  Registered adapter: ***=1.8.2
[2024-10-15T23:12:52.502+0000] {subprocess.py:93} INFO - [0m23:12:52  Found 1 model, 1 source, 540 macros
[2024-10-15T23:12:52.505+0000] {subprocess.py:93} INFO - [0m23:12:52
[2024-10-15T23:12:52.705+0000] {subprocess.py:93} INFO - [0m23:12:52  Concurrency: 4 threads (target='dev')
[2024-10-15T23:12:52.706+0000] {subprocess.py:93} INFO - [0m23:12:52
[2024-10-15T23:12:52.718+0000] {subprocess.py:93} INFO - [0m23:12:52  1 of 1 START sql table model analytics.stg_kaggle__btcusdt ..................... [RUN]
[2024-10-15T23:12:52.831+0000] {subprocess.py:93} INFO - [0m23:12:52  1 of 1 ERROR creating sql table model analytics.stg_kaggle__btcusdt ............ [[31mERROR[0m in 0.11s]
[2024-10-15T23:12:52.852+0000] {subprocess.py:93} INFO - [0m23:12:52
[2024-10-15T23:12:52.853+0000] {subprocess.py:93} INFO - [0m23:12:52  Finished running 1 table model in 0 hours 0 minutes and 0.35 seconds (0.35s).
[2024-10-15T23:12:52.856+0000] {subprocess.py:93} INFO - [0m23:12:52
[2024-10-15T23:12:52.857+0000] {subprocess.py:93} INFO - [0m23:12:52  [31mCompleted with 1 error and 0 warnings:[0m
[2024-10-15T23:12:52.858+0000] {subprocess.py:93} INFO - [0m23:12:52
[2024-10-15T23:12:52.859+0000] {subprocess.py:93} INFO - [0m23:12:52    Database Error in model stg_kaggle__btcusdt (models/staging/kaggle/stg_kaggle__btcusdt.sql)
[2024-10-15T23:12:52.859+0000] {subprocess.py:93} INFO -   column "quote" does not exist
[2024-10-15T23:12:52.859+0000] {subprocess.py:93} INFO -   LINE 31:         quote,
[2024-10-15T23:12:52.860+0000] {subprocess.py:93} INFO -                    ^
[2024-10-15T23:12:52.860+0000] {subprocess.py:93} INFO -   compiled code at target/run/dbt_btc_transform/models/staging/kaggle/stg_kaggle__btcusdt.sql
[2024-10-15T23:12:52.860+0000] {subprocess.py:93} INFO - [0m23:12:52
[2024-10-15T23:12:52.861+0000] {subprocess.py:93} INFO - [0m23:12:52  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
[2024-10-15T23:12:53.479+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-10-15T23:12:53.481+0000] {taskinstance.py:789} DEBUG - Refreshing TaskInstance <TaskInstance: run_dbt_models.model.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:12:44.688778+00:00 [running]> from DB
[2024-10-15T23:12:53.501+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-10-15T23:12:53.502+0000] {taskinstance.py:789} DEBUG - Refreshing TaskInstance <TaskInstance: run_dbt_models.model.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:12:44.688778+00:00 [running]> from DB
[2024-10-15T23:12:53.505+0000] {taskinstance.py:2305} DEBUG - Task Duration set to 4.347582
[2024-10-15T23:12:53.508+0000] {taskinstance.py:1356} DEBUG - Clearing next_method and next_kwargs.
[2024-10-15T23:12:53.508+0000] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=run_dbt_models, task_id=model.dbt_btc_transform.stg_kaggle__btcusdt, execution_date=20241015T231244, start_date=20241015T231249, end_date=20241015T231253
[2024-10-15T23:12:53.527+0000] {cli_action_loggers.py:83} DEBUG - Calling callbacks: []
[2024-10-15T23:12:53.527+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 41 for task model.dbt_btc_transform.stg_kaggle__btcusdt (Bash command failed. The command returned a non-zero exit code 1.; 822)
[2024-10-15T23:12:53.557+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-10-15T23:12:53.619+0000] {dagrun.py:697} DEBUG - number of tis tasks for <DagRun run_dbt_models @ 2024-10-15 23:12:44.688778+00:00: manual__2024-10-15T23:12:44.688778+00:00, state:running, queued_at: 2024-10-15 23:12:44.695918+00:00. externally triggered: True>: 4 task(s)
[2024-10-15T23:12:53.619+0000] {dagrun.py:718} DEBUG - number of scheduleable tasks for <DagRun run_dbt_models @ 2024-10-15 23:12:44.688778+00:00: manual__2024-10-15T23:12:44.688778+00:00, state:running, queued_at: 2024-10-15 23:12:44.695918+00:00. externally triggered: True>: 3 task(s)
[2024-10-15T23:12:53.622+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-15T23:12:44.688778+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, This task instance was the first task instance for its task.
[2024-10-15T23:12:53.622+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-15T23:12:44.688778+00:00 [None]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 2 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0), upstream_task_ids={'model.dbt_btc_transform.stg_kaggle__btcusdt', 'test.dbt_btc_transform.stg_kaggle__btcusdt'}
[2024-10-15T23:12:53.623+0000] {taskinstance.py:1093} DEBUG - Dependencies not met for <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-15T23:12:44.688778+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 2 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0), upstream_task_ids={'model.dbt_btc_transform.stg_kaggle__btcusdt', 'test.dbt_btc_transform.stg_kaggle__btcusdt'}
[2024-10-15T23:12:53.623+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-15T23:12:44.688778+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-10-15T23:12:53.625+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.test.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:12:44.688778+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, This task instance was the first task instance for its task.
[2024-10-15T23:12:53.628+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.test.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:12:44.688778+00:00 [None]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=1, skipped=0, failed=0, upstream_failed=0, removed=0, done=1), upstream_task_ids={'model.dbt_btc_transform.stg_kaggle__btcusdt', 'wait_for_dbt_init'}
[2024-10-15T23:12:53.628+0000] {taskinstance.py:1093} DEBUG - Dependencies not met for <TaskInstance: run_dbt_models.test.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:12:44.688778+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=1, skipped=0, failed=0, upstream_failed=0, removed=0, done=1), upstream_task_ids={'model.dbt_btc_transform.stg_kaggle__btcusdt', 'wait_for_dbt_init'}
[2024-10-15T23:12:53.629+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.test.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:12:44.688778+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-10-15T23:12:53.630+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.model.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:12:44.688778+00:00 [up_for_retry]> dependency 'Previous Dagrun State' PASSED: True, This task instance was the first task instance for its task.
[2024-10-15T23:12:53.633+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.model.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:12:44.688778+00:00 [up_for_retry]> dependency 'Not In Retry Period' PASSED: False, Task is not ready for retry yet but will be retried automatically. Current date is 2024-10-15T23:12:53.633016+00:00 and task will be retried at 2024-10-15T23:17:53.505487+00:00.
[2024-10-15T23:12:53.633+0000] {taskinstance.py:1093} DEBUG - Dependencies not met for <TaskInstance: run_dbt_models.model.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:12:44.688778+00:00 [up_for_retry]>, dependency 'Not In Retry Period' FAILED: Task is not ready for retry yet but will be retried automatically. Current date is 2024-10-15T23:12:53.633016+00:00 and task will be retried at 2024-10-15T23:17:53.505487+00:00.
[2024-10-15T23:12:53.640+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
