[2024-10-15T23:11:02.505+0000] {taskinstance.py:1037} DEBUG - previous_execution_date was called
[2024-10-15T23:11:02.528+0000] {__init__.py:51} DEBUG - Loading core task runner: StandardTaskRunner
[2024-10-15T23:11:02.543+0000] {taskinstance.py:1037} DEBUG - previous_execution_date was called
[2024-10-15T23:11:02.550+0000] {base_task_runner.py:68} DEBUG - Planning to run as the  user
[2024-10-15T23:11:02.552+0000] {taskinstance.py:789} DEBUG - Refreshing TaskInstance <TaskInstance: run_dbt_models.model.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:05:52.533157+00:00 [queued]> from DB
[2024-10-15T23:11:02.579+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.model.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:05:52.533157+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, This task instance was the first task instance for its task.
[2024-10-15T23:11:02.592+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.model.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:05:52.533157+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2024-10-15T23:11:02.592+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.model.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:05:52.533157+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2024-10-15T23:11:02.593+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.model.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:05:52.533157+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-10-15T23:11:02.593+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_dbt_models.model.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:05:52.533157+00:00 [queued]>
[2024-10-15T23:11:02.595+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.model.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:05:52.533157+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, This task instance was the first task instance for its task.
[2024-10-15T23:11:02.601+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.model.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:05:52.533157+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2024-10-15T23:11:02.607+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.model.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:05:52.533157+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2024-10-15T23:11:02.607+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.model.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:05:52.533157+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-10-15T23:11:02.607+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_dbt_models.model.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:05:52.533157+00:00 [queued]>
[2024-10-15T23:11:02.608+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2024-10-15T23:11:02.622+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): model.dbt_btc_transform.stg_kaggle__btcusdt> on 2024-10-15 23:05:52.533157+00:00
[2024-10-15T23:11:02.626+0000] {standard_task_runner.py:57} INFO - Started process 738 to run task
[2024-10-15T23:11:02.630+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'run_dbt_models', 'model.dbt_btc_transform.stg_kaggle__btcusdt', 'manual__2024-10-15T23:05:52.533157+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/run_dbt_models.py', '--cfg-path', '/tmp/tmp2l8j092w']
[2024-10-15T23:11:02.631+0000] {standard_task_runner.py:85} INFO - Job 38: Subtask model.dbt_btc_transform.stg_kaggle__btcusdt
[2024-10-15T23:11:02.632+0000] {cli_action_loggers.py:65} DEBUG - Calling callbacks: [<function default_action_log at 0x7f7b0c199c10>]
[2024-10-15T23:11:02.698+0000] {taskinstance.py:1037} DEBUG - previous_execution_date was called
[2024-10-15T23:11:02.707+0000] {task_command.py:410} INFO - Running <TaskInstance: run_dbt_models.model.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:05:52.533157+00:00 [running]> on host d867809303f2
[2024-10-15T23:11:02.708+0000] {settings.py:353} DEBUG - Disposing DB connection pool (PID 738)
[2024-10-15T23:11:02.708+0000] {settings.py:212} DEBUG - Setting up DB connection pool (PID 738)
[2024-10-15T23:11:02.709+0000] {settings.py:285} DEBUG - settings.prepare_engine_args(): Using NullPool
[2024-10-15T23:11:02.711+0000] {taskinstance.py:789} DEBUG - Refreshing TaskInstance <TaskInstance: run_dbt_models.model.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:05:52.533157+00:00 [running]> from DB
[2024-10-15T23:11:02.760+0000] {taskinstance.py:1037} DEBUG - previous_execution_date was called
[2024-10-15T23:11:02.770+0000] {taskinstance.py:868} DEBUG - Clearing XCom data
[2024-10-15T23:11:02.803+0000] {retries.py:80} DEBUG - Running RenderedTaskInstanceFields._do_delete_old_records with retries. Try 1 of 3
[2024-10-15T23:11:02.819+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='airflow@example.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='run_dbt_models' AIRFLOW_CTX_TASK_ID='model.dbt_btc_transform.stg_kaggle__btcusdt' AIRFLOW_CTX_EXECUTION_DATE='2024-10-15T23:05:52.533157+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-15T23:05:52.533157+00:00'
[2024-10-15T23:11:02.819+0000] {__init__.py:117} DEBUG - Preparing lineage inlets and outlets
[2024-10-15T23:11:02.820+0000] {__init__.py:155} DEBUG - inlets: [], outlets: []
[2024-10-15T23:11:02.821+0000] {bash.py:186} DEBUG - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='airflow@example.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='run_dbt_models' AIRFLOW_CTX_TASK_ID='model.dbt_btc_transform.stg_kaggle__btcusdt' AIRFLOW_CTX_EXECUTION_DATE='2024-10-15T23:05:52.533157+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-15T23:05:52.533157+00:00'
[2024-10-15T23:11:02.822+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-10-15T23:11:02.822+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n            export DBT_SCHEMA=analytics &&\n            cd /opt/airflow/dbt &&\n            /home/airflow/.local/bin/dbt --no-write-json run --target dev --models stg_kaggle__btcusdt\n            ']
[2024-10-15T23:11:02.832+0000] {subprocess.py:86} INFO - Output:
[2024-10-15T23:11:05.009+0000] {subprocess.py:93} INFO - [0m23:11:05  Running with dbt=1.8.7
[2024-10-15T23:11:05.326+0000] {subprocess.py:93} INFO - [0m23:11:05  Registered adapter: ***=1.8.2
[2024-10-15T23:11:05.495+0000] {subprocess.py:93} INFO - [0m23:11:05  Unable to do partial parsing because of a version mismatch
[2024-10-15T23:11:07.616+0000] {subprocess.py:93} INFO - [0m23:11:07  Found 1 model, 1 source, 540 macros
[2024-10-15T23:11:07.619+0000] {subprocess.py:93} INFO - [0m23:11:07
[2024-10-15T23:11:07.659+0000] {taskinstance.py:789} DEBUG - Refreshing TaskInstance <TaskInstance: run_dbt_models.model.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:05:52.533157+00:00 [running]> from DB
[2024-10-15T23:11:07.674+0000] {job.py:213} DEBUG - [heartbeat]
[2024-10-15T23:11:07.796+0000] {subprocess.py:93} INFO - [0m23:11:07  Concurrency: 4 threads (target='dev')
[2024-10-15T23:11:07.797+0000] {subprocess.py:93} INFO - [0m23:11:07
[2024-10-15T23:11:07.808+0000] {subprocess.py:93} INFO - [0m23:11:07  1 of 1 START sql table model analytics.stg_kaggle__btcusdt ..................... [RUN]
[2024-10-15T23:11:07.912+0000] {subprocess.py:93} INFO - [0m23:11:07  1 of 1 ERROR creating sql table model analytics.stg_kaggle__btcusdt ............ [[31mERROR[0m in 0.10s]
[2024-10-15T23:11:07.932+0000] {subprocess.py:93} INFO - [0m23:11:07
[2024-10-15T23:11:07.933+0000] {subprocess.py:93} INFO - [0m23:11:07  Finished running 1 table model in 0 hours 0 minutes and 0.31 seconds (0.31s).
[2024-10-15T23:11:07.935+0000] {subprocess.py:93} INFO - [0m23:11:07
[2024-10-15T23:11:07.936+0000] {subprocess.py:93} INFO - [0m23:11:07  [31mCompleted with 1 error and 0 warnings:[0m
[2024-10-15T23:11:07.937+0000] {subprocess.py:93} INFO - [0m23:11:07
[2024-10-15T23:11:07.939+0000] {subprocess.py:93} INFO - [0m23:11:07    Database Error in model stg_kaggle__btcusdt (models/staging/kaggle/stg_kaggle__btcusdt.sql)
[2024-10-15T23:11:07.939+0000] {subprocess.py:93} INFO -   column "quote" does not exist
[2024-10-15T23:11:07.939+0000] {subprocess.py:93} INFO -   LINE 31:         quote,
[2024-10-15T23:11:07.940+0000] {subprocess.py:93} INFO -                    ^
[2024-10-15T23:11:07.940+0000] {subprocess.py:93} INFO -   compiled code at target/run/dbt_btc_transform/models/staging/kaggle/stg_kaggle__btcusdt.sql
[2024-10-15T23:11:07.940+0000] {subprocess.py:93} INFO - [0m23:11:07
[2024-10-15T23:11:07.941+0000] {subprocess.py:93} INFO - [0m23:11:07  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
[2024-10-15T23:11:08.593+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-10-15T23:11:08.594+0000] {taskinstance.py:789} DEBUG - Refreshing TaskInstance <TaskInstance: run_dbt_models.model.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:05:52.533157+00:00 [running]> from DB
[2024-10-15T23:11:08.613+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-10-15T23:11:08.614+0000] {taskinstance.py:789} DEBUG - Refreshing TaskInstance <TaskInstance: run_dbt_models.model.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:05:52.533157+00:00 [running]> from DB
[2024-10-15T23:11:08.616+0000] {taskinstance.py:2305} DEBUG - Task Duration set to 6.022692
[2024-10-15T23:11:08.619+0000] {taskinstance.py:1356} DEBUG - Clearing next_method and next_kwargs.
[2024-10-15T23:11:08.619+0000] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=run_dbt_models, task_id=model.dbt_btc_transform.stg_kaggle__btcusdt, execution_date=20241015T230552, start_date=20241015T231102, end_date=20241015T231108
[2024-10-15T23:11:08.636+0000] {cli_action_loggers.py:83} DEBUG - Calling callbacks: []
[2024-10-15T23:11:08.637+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 38 for task model.dbt_btc_transform.stg_kaggle__btcusdt (Bash command failed. The command returned a non-zero exit code 1.; 738)
[2024-10-15T23:11:08.676+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-10-15T23:11:08.737+0000] {dagrun.py:697} DEBUG - number of tis tasks for <DagRun run_dbt_models @ 2024-10-15 23:05:52.533157+00:00: manual__2024-10-15T23:05:52.533157+00:00, state:running, queued_at: 2024-10-15 23:05:52.544036+00:00. externally triggered: True>: 4 task(s)
[2024-10-15T23:11:08.738+0000] {dagrun.py:718} DEBUG - number of scheduleable tasks for <DagRun run_dbt_models @ 2024-10-15 23:05:52.533157+00:00: manual__2024-10-15T23:05:52.533157+00:00, state:running, queued_at: 2024-10-15 23:05:52.544036+00:00. externally triggered: True>: 2 task(s)
[2024-10-15T23:11:08.740+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-15T23:05:52.533157+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, This task instance was the first task instance for its task.
[2024-10-15T23:11:08.740+0000] {taskinstance.py:899} DEBUG - Setting task state for <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-15T23:05:52.533157+00:00 [None]> to upstream_failed
[2024-10-15T23:11:08.741+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-15T23:05:52.533157+00:00 [upstream_failed]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 2 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=1, upstream_failed=0, removed=0, done=1), upstream_task_ids={'model.dbt_btc_transform.stg_kaggle__btcusdt', 'test.dbt_btc_transform.stg_kaggle__btcusdt'}
[2024-10-15T23:11:08.741+0000] {taskinstance.py:1093} DEBUG - Dependencies not met for <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-15T23:05:52.533157+00:00 [upstream_failed]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 2 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=1, upstream_failed=0, removed=0, done=1), upstream_task_ids={'model.dbt_btc_transform.stg_kaggle__btcusdt', 'test.dbt_btc_transform.stg_kaggle__btcusdt'}
[2024-10-15T23:11:08.742+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-15T23:05:52.533157+00:00 [upstream_failed]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-10-15T23:11:08.743+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.test.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:05:52.533157+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, This task instance was the first task instance for its task.
[2024-10-15T23:11:08.746+0000] {taskinstance.py:899} DEBUG - Setting task state for <TaskInstance: run_dbt_models.test.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:05:52.533157+00:00 [None]> to upstream_failed
[2024-10-15T23:11:08.746+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.test.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:05:52.533157+00:00 [upstream_failed]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=1, skipped=0, failed=1, upstream_failed=0, removed=0, done=2), upstream_task_ids={'model.dbt_btc_transform.stg_kaggle__btcusdt', 'wait_for_dbt_init'}
[2024-10-15T23:11:08.746+0000] {taskinstance.py:1093} DEBUG - Dependencies not met for <TaskInstance: run_dbt_models.test.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:05:52.533157+00:00 [upstream_failed]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=1, skipped=0, failed=1, upstream_failed=0, removed=0, done=2), upstream_task_ids={'model.dbt_btc_transform.stg_kaggle__btcusdt', 'wait_for_dbt_init'}
[2024-10-15T23:11:08.747+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.test.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:05:52.533157+00:00 [upstream_failed]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-10-15T23:11:08.751+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
