[2024-10-15T23:12:39.916+0000] {taskinstance.py:1037} DEBUG - previous_execution_date was called
[2024-10-15T23:12:39.949+0000] {__init__.py:51} DEBUG - Loading core task runner: StandardTaskRunner
[2024-10-15T23:12:39.968+0000] {taskinstance.py:1037} DEBUG - previous_execution_date was called
[2024-10-15T23:12:39.977+0000] {base_task_runner.py:68} DEBUG - Planning to run as the  user
[2024-10-15T23:12:39.980+0000] {taskinstance.py:789} DEBUG - Refreshing TaskInstance <TaskInstance: run_dbt_models.model.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:07:20.618561+00:00 [queued]> from DB
[2024-10-15T23:12:40.010+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.model.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:07:20.618561+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, This task instance was the first task instance for its task.
[2024-10-15T23:12:40.022+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.model.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:07:20.618561+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2024-10-15T23:12:40.023+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.model.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:07:20.618561+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2024-10-15T23:12:40.023+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.model.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:07:20.618561+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-10-15T23:12:40.023+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_dbt_models.model.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:07:20.618561+00:00 [queued]>
[2024-10-15T23:12:40.026+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.model.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:07:20.618561+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, This task instance was the first task instance for its task.
[2024-10-15T23:12:40.032+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.model.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:07:20.618561+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2024-10-15T23:12:40.038+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.model.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:07:20.618561+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2024-10-15T23:12:40.038+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.model.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:07:20.618561+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-10-15T23:12:40.038+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_dbt_models.model.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:07:20.618561+00:00 [queued]>
[2024-10-15T23:12:40.039+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2024-10-15T23:12:40.052+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): model.dbt_btc_transform.stg_kaggle__btcusdt> on 2024-10-15 23:07:20.618561+00:00
[2024-10-15T23:12:40.056+0000] {standard_task_runner.py:57} INFO - Started process 793 to run task
[2024-10-15T23:12:40.060+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'run_dbt_models', 'model.dbt_btc_transform.stg_kaggle__btcusdt', 'manual__2024-10-15T23:07:20.618561+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/run_dbt_models.py', '--cfg-path', '/tmp/tmps44e33e2']
[2024-10-15T23:12:40.060+0000] {standard_task_runner.py:85} INFO - Job 39: Subtask model.dbt_btc_transform.stg_kaggle__btcusdt
[2024-10-15T23:12:40.061+0000] {cli_action_loggers.py:65} DEBUG - Calling callbacks: [<function default_action_log at 0x7f7b0c199c10>]
[2024-10-15T23:12:40.123+0000] {taskinstance.py:1037} DEBUG - previous_execution_date was called
[2024-10-15T23:12:40.131+0000] {task_command.py:410} INFO - Running <TaskInstance: run_dbt_models.model.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:07:20.618561+00:00 [running]> on host d867809303f2
[2024-10-15T23:12:40.132+0000] {settings.py:353} DEBUG - Disposing DB connection pool (PID 793)
[2024-10-15T23:12:40.132+0000] {settings.py:212} DEBUG - Setting up DB connection pool (PID 793)
[2024-10-15T23:12:40.133+0000] {settings.py:285} DEBUG - settings.prepare_engine_args(): Using NullPool
[2024-10-15T23:12:40.135+0000] {taskinstance.py:789} DEBUG - Refreshing TaskInstance <TaskInstance: run_dbt_models.model.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:07:20.618561+00:00 [running]> from DB
[2024-10-15T23:12:40.183+0000] {taskinstance.py:1037} DEBUG - previous_execution_date was called
[2024-10-15T23:12:40.196+0000] {taskinstance.py:868} DEBUG - Clearing XCom data
[2024-10-15T23:12:40.234+0000] {retries.py:80} DEBUG - Running RenderedTaskInstanceFields._do_delete_old_records with retries. Try 1 of 3
[2024-10-15T23:12:40.251+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='airflow@example.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='run_dbt_models' AIRFLOW_CTX_TASK_ID='model.dbt_btc_transform.stg_kaggle__btcusdt' AIRFLOW_CTX_EXECUTION_DATE='2024-10-15T23:07:20.618561+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-15T23:07:20.618561+00:00'
[2024-10-15T23:12:40.252+0000] {__init__.py:117} DEBUG - Preparing lineage inlets and outlets
[2024-10-15T23:12:40.252+0000] {__init__.py:155} DEBUG - inlets: [], outlets: []
[2024-10-15T23:12:40.253+0000] {bash.py:186} DEBUG - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='airflow@example.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='run_dbt_models' AIRFLOW_CTX_TASK_ID='model.dbt_btc_transform.stg_kaggle__btcusdt' AIRFLOW_CTX_EXECUTION_DATE='2024-10-15T23:07:20.618561+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-15T23:07:20.618561+00:00'
[2024-10-15T23:12:40.254+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-10-15T23:12:40.254+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n            export DBT_SCHEMA=analytics &&\n            cd /opt/airflow/dbt &&\n            /home/airflow/.local/bin/dbt --no-write-json run --target dev --models stg_kaggle__btcusdt\n            ']
[2024-10-15T23:12:40.263+0000] {subprocess.py:86} INFO - Output:
[2024-10-15T23:12:42.701+0000] {subprocess.py:93} INFO - [0m23:12:42  Running with dbt=1.8.7
[2024-10-15T23:12:43.031+0000] {subprocess.py:93} INFO - [0m23:12:43  Registered adapter: ***=1.8.2
[2024-10-15T23:12:43.220+0000] {subprocess.py:93} INFO - [0m23:12:43  Unable to do partial parsing because of a version mismatch
[2024-10-15T23:12:45.099+0000] {taskinstance.py:789} DEBUG - Refreshing TaskInstance <TaskInstance: run_dbt_models.model.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:07:20.618561+00:00 [running]> from DB
[2024-10-15T23:12:45.119+0000] {job.py:213} DEBUG - [heartbeat]
[2024-10-15T23:12:45.669+0000] {subprocess.py:93} INFO - [0m23:12:45  Found 1 model, 1 source, 540 macros
[2024-10-15T23:12:45.672+0000] {subprocess.py:93} INFO - [0m23:12:45
[2024-10-15T23:12:45.852+0000] {subprocess.py:93} INFO - [0m23:12:45  Concurrency: 4 threads (target='dev')
[2024-10-15T23:12:45.853+0000] {subprocess.py:93} INFO - [0m23:12:45
[2024-10-15T23:12:45.865+0000] {subprocess.py:93} INFO - [0m23:12:45  1 of 1 START sql table model analytics.stg_kaggle__btcusdt ..................... [RUN]
[2024-10-15T23:12:45.969+0000] {subprocess.py:93} INFO - [0m23:12:45  1 of 1 ERROR creating sql table model analytics.stg_kaggle__btcusdt ............ [[31mERROR[0m in 0.10s]
[2024-10-15T23:12:45.988+0000] {subprocess.py:93} INFO - [0m23:12:45
[2024-10-15T23:12:45.989+0000] {subprocess.py:93} INFO - [0m23:12:45  Finished running 1 table model in 0 hours 0 minutes and 0.31 seconds (0.31s).
[2024-10-15T23:12:45.991+0000] {subprocess.py:93} INFO - [0m23:12:45
[2024-10-15T23:12:45.992+0000] {subprocess.py:93} INFO - [0m23:12:45  [31mCompleted with 1 error and 0 warnings:[0m
[2024-10-15T23:12:45.992+0000] {subprocess.py:93} INFO - [0m23:12:45
[2024-10-15T23:12:45.993+0000] {subprocess.py:93} INFO - [0m23:12:45    Database Error in model stg_kaggle__btcusdt (models/staging/kaggle/stg_kaggle__btcusdt.sql)
[2024-10-15T23:12:45.994+0000] {subprocess.py:93} INFO -   column "quote" does not exist
[2024-10-15T23:12:45.994+0000] {subprocess.py:93} INFO -   LINE 31:         quote,
[2024-10-15T23:12:45.994+0000] {subprocess.py:93} INFO -                    ^
[2024-10-15T23:12:45.994+0000] {subprocess.py:93} INFO -   compiled code at target/run/dbt_btc_transform/models/staging/kaggle/stg_kaggle__btcusdt.sql
[2024-10-15T23:12:45.995+0000] {subprocess.py:93} INFO - [0m23:12:45
[2024-10-15T23:12:45.995+0000] {subprocess.py:93} INFO - [0m23:12:45  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
[2024-10-15T23:12:46.678+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-10-15T23:12:46.679+0000] {taskinstance.py:789} DEBUG - Refreshing TaskInstance <TaskInstance: run_dbt_models.model.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:07:20.618561+00:00 [running]> from DB
[2024-10-15T23:12:46.698+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-10-15T23:12:46.699+0000] {taskinstance.py:789} DEBUG - Refreshing TaskInstance <TaskInstance: run_dbt_models.model.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:07:20.618561+00:00 [running]> from DB
[2024-10-15T23:12:46.701+0000] {taskinstance.py:2305} DEBUG - Task Duration set to 6.677683
[2024-10-15T23:12:46.704+0000] {taskinstance.py:1356} DEBUG - Clearing next_method and next_kwargs.
[2024-10-15T23:12:46.705+0000] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=run_dbt_models, task_id=model.dbt_btc_transform.stg_kaggle__btcusdt, execution_date=20241015T230720, start_date=20241015T231240, end_date=20241015T231246
[2024-10-15T23:12:46.722+0000] {cli_action_loggers.py:83} DEBUG - Calling callbacks: []
[2024-10-15T23:12:46.723+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 39 for task model.dbt_btc_transform.stg_kaggle__btcusdt (Bash command failed. The command returned a non-zero exit code 1.; 793)
[2024-10-15T23:12:46.736+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-10-15T23:12:46.791+0000] {dagrun.py:697} DEBUG - number of tis tasks for <DagRun run_dbt_models @ 2024-10-15 23:07:20.618561+00:00: manual__2024-10-15T23:07:20.618561+00:00, state:running, queued_at: 2024-10-15 23:07:20.626118+00:00. externally triggered: True>: 4 task(s)
[2024-10-15T23:12:46.791+0000] {dagrun.py:718} DEBUG - number of scheduleable tasks for <DagRun run_dbt_models @ 2024-10-15 23:07:20.618561+00:00: manual__2024-10-15T23:07:20.618561+00:00, state:running, queued_at: 2024-10-15 23:07:20.626118+00:00. externally triggered: True>: 2 task(s)
[2024-10-15T23:12:46.793+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-15T23:07:20.618561+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, This task instance was the first task instance for its task.
[2024-10-15T23:12:46.794+0000] {taskinstance.py:899} DEBUG - Setting task state for <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-15T23:07:20.618561+00:00 [None]> to upstream_failed
[2024-10-15T23:12:46.794+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-15T23:07:20.618561+00:00 [upstream_failed]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 2 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=1, upstream_failed=0, removed=0, done=1), upstream_task_ids={'model.dbt_btc_transform.stg_kaggle__btcusdt', 'test.dbt_btc_transform.stg_kaggle__btcusdt'}
[2024-10-15T23:12:46.795+0000] {taskinstance.py:1093} DEBUG - Dependencies not met for <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-15T23:07:20.618561+00:00 [upstream_failed]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 2 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=1, upstream_failed=0, removed=0, done=1), upstream_task_ids={'model.dbt_btc_transform.stg_kaggle__btcusdt', 'test.dbt_btc_transform.stg_kaggle__btcusdt'}
[2024-10-15T23:12:46.795+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-15T23:07:20.618561+00:00 [upstream_failed]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-10-15T23:12:46.796+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.test.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:07:20.618561+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, This task instance was the first task instance for its task.
[2024-10-15T23:12:46.799+0000] {taskinstance.py:899} DEBUG - Setting task state for <TaskInstance: run_dbt_models.test.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:07:20.618561+00:00 [None]> to upstream_failed
[2024-10-15T23:12:46.800+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.test.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:07:20.618561+00:00 [upstream_failed]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=1, skipped=0, failed=1, upstream_failed=0, removed=0, done=2), upstream_task_ids={'model.dbt_btc_transform.stg_kaggle__btcusdt', 'wait_for_dbt_init'}
[2024-10-15T23:12:46.800+0000] {taskinstance.py:1093} DEBUG - Dependencies not met for <TaskInstance: run_dbt_models.test.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:07:20.618561+00:00 [upstream_failed]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=1, skipped=0, failed=1, upstream_failed=0, removed=0, done=2), upstream_task_ids={'model.dbt_btc_transform.stg_kaggle__btcusdt', 'wait_for_dbt_init'}
[2024-10-15T23:12:46.800+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.test.dbt_btc_transform.stg_kaggle__btcusdt manual__2024-10-15T23:07:20.618561+00:00 [upstream_failed]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-10-15T23:12:46.805+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
