[2024-10-15T23:18:06.369+0000] {taskinstance.py:1037} DEBUG - previous_execution_date was called
[2024-10-15T23:18:06.392+0000] {__init__.py:51} DEBUG - Loading core task runner: StandardTaskRunner
[2024-10-15T23:18:06.407+0000] {taskinstance.py:1037} DEBUG - previous_execution_date was called
[2024-10-15T23:18:06.414+0000] {base_task_runner.py:68} DEBUG - Planning to run as the  user
[2024-10-15T23:18:06.417+0000] {taskinstance.py:789} DEBUG - Refreshing TaskInstance <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-15T23:12:44.688778+00:00 [queued]> from DB
[2024-10-15T23:18:06.441+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-15T23:12:44.688778+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, This task instance was the first task instance for its task.
[2024-10-15T23:18:06.447+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-15T23:12:44.688778+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2024-10-15T23:18:06.447+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-15T23:12:44.688778+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2024-10-15T23:18:06.448+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-15T23:12:44.688778+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-10-15T23:18:06.448+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-15T23:12:44.688778+00:00 [queued]>
[2024-10-15T23:18:06.449+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-15T23:12:44.688778+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, This task instance was the first task instance for its task.
[2024-10-15T23:18:06.453+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-15T23:12:44.688778+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2024-10-15T23:18:06.458+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-15T23:12:44.688778+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2024-10-15T23:18:06.458+0000] {taskinstance.py:1112} DEBUG - <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-15T23:12:44.688778+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-10-15T23:18:06.458+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-15T23:12:44.688778+00:00 [queued]>
[2024-10-15T23:18:06.459+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-10-15T23:18:06.470+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): generate_dbt_docs> on 2024-10-15 23:12:44.688778+00:00
[2024-10-15T23:18:06.473+0000] {standard_task_runner.py:57} INFO - Started process 1066 to run task
[2024-10-15T23:18:06.476+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'run_dbt_models', 'generate_dbt_docs', 'manual__2024-10-15T23:12:44.688778+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/run_dbt_models.py', '--cfg-path', '/tmp/tmpt7zw4jgl']
[2024-10-15T23:18:06.477+0000] {standard_task_runner.py:85} INFO - Job 51: Subtask generate_dbt_docs
[2024-10-15T23:18:06.478+0000] {cli_action_loggers.py:65} DEBUG - Calling callbacks: [<function default_action_log at 0x7f7b0c199c10>]
[2024-10-15T23:18:06.529+0000] {taskinstance.py:1037} DEBUG - previous_execution_date was called
[2024-10-15T23:18:06.537+0000] {task_command.py:410} INFO - Running <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-15T23:12:44.688778+00:00 [running]> on host d867809303f2
[2024-10-15T23:18:06.537+0000] {settings.py:353} DEBUG - Disposing DB connection pool (PID 1066)
[2024-10-15T23:18:06.538+0000] {settings.py:212} DEBUG - Setting up DB connection pool (PID 1066)
[2024-10-15T23:18:06.538+0000] {settings.py:285} DEBUG - settings.prepare_engine_args(): Using NullPool
[2024-10-15T23:18:06.540+0000] {taskinstance.py:789} DEBUG - Refreshing TaskInstance <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-15T23:12:44.688778+00:00 [running]> from DB
[2024-10-15T23:18:06.581+0000] {taskinstance.py:1037} DEBUG - previous_execution_date was called
[2024-10-15T23:18:06.590+0000] {taskinstance.py:868} DEBUG - Clearing XCom data
[2024-10-15T23:18:06.624+0000] {retries.py:80} DEBUG - Running RenderedTaskInstanceFields._do_delete_old_records with retries. Try 1 of 3
[2024-10-15T23:18:06.637+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='airflow@example.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='run_dbt_models' AIRFLOW_CTX_TASK_ID='generate_dbt_docs' AIRFLOW_CTX_EXECUTION_DATE='2024-10-15T23:12:44.688778+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-15T23:12:44.688778+00:00'
[2024-10-15T23:18:06.638+0000] {__init__.py:117} DEBUG - Preparing lineage inlets and outlets
[2024-10-15T23:18:06.638+0000] {__init__.py:155} DEBUG - inlets: [], outlets: []
[2024-10-15T23:18:06.639+0000] {bash.py:186} DEBUG - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='airflow@example.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='run_dbt_models' AIRFLOW_CTX_TASK_ID='generate_dbt_docs' AIRFLOW_CTX_EXECUTION_DATE='2024-10-15T23:12:44.688778+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-15T23:12:44.688778+00:00'
[2024-10-15T23:18:06.640+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-10-15T23:18:06.640+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'dbt docs generate --profiles-dir /opt/airflow/dbt --project-dir /opt/airflow/dbt']
[2024-10-15T23:18:06.647+0000] {subprocess.py:86} INFO - Output:
[2024-10-15T23:18:08.717+0000] {subprocess.py:93} INFO - [0m23:18:08  Running with dbt=1.8.7
[2024-10-15T23:18:09.016+0000] {subprocess.py:93} INFO - [0m23:18:09  Registered adapter: ***=1.8.2
[2024-10-15T23:18:09.179+0000] {subprocess.py:93} INFO - [0m23:18:09  Unable to do partial parsing because config vars, config profile, or config target have changed
[2024-10-15T23:18:09.181+0000] {subprocess.py:93} INFO - [0m23:18:09  Unable to do partial parsing because profile has changed
[2024-10-15T23:18:11.294+0000] {subprocess.py:93} INFO - [0m23:18:11  Found 1 model, 1 source, 540 macros
[2024-10-15T23:18:11.297+0000] {subprocess.py:93} INFO - [0m23:18:11
[2024-10-15T23:18:11.450+0000] {subprocess.py:93} INFO - [0m23:18:11  Concurrency: 4 threads (target='dev')
[2024-10-15T23:18:11.451+0000] {subprocess.py:93} INFO - [0m23:18:11
[2024-10-15T23:18:11.508+0000] {taskinstance.py:789} DEBUG - Refreshing TaskInstance <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-15T23:12:44.688778+00:00 [running]> from DB
[2024-10-15T23:18:11.522+0000] {job.py:213} DEBUG - [heartbeat]
[2024-10-15T23:18:11.672+0000] {subprocess.py:93} INFO - [0m23:18:11  Building catalog
[2024-10-15T23:18:11.799+0000] {subprocess.py:93} INFO - [0m23:18:11  Catalog written to /opt/airflow/dbt/target/catalog.json
[2024-10-15T23:18:12.401+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-10-15T23:18:12.428+0000] {__init__.py:75} DEBUG - Lineage called with inlets: [], outlets: []
[2024-10-15T23:18:12.428+0000] {taskinstance.py:789} DEBUG - Refreshing TaskInstance <TaskInstance: run_dbt_models.generate_dbt_docs manual__2024-10-15T23:12:44.688778+00:00 [running]> from DB
[2024-10-15T23:18:12.442+0000] {taskinstance.py:1356} DEBUG - Clearing next_method and next_kwargs.
[2024-10-15T23:18:12.443+0000] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=run_dbt_models, task_id=generate_dbt_docs, execution_date=20241015T231244, start_date=20241015T231806, end_date=20241015T231812
[2024-10-15T23:18:12.443+0000] {taskinstance.py:2305} DEBUG - Task Duration set to 5.994601
[2024-10-15T23:18:12.456+0000] {cli_action_loggers.py:83} DEBUG - Calling callbacks: []
[2024-10-15T23:18:12.482+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2024-10-15T23:18:12.539+0000] {dagrun.py:697} DEBUG - number of tis tasks for <DagRun run_dbt_models @ 2024-10-15 23:12:44.688778+00:00: manual__2024-10-15T23:12:44.688778+00:00, state:running, queued_at: 2024-10-15 23:12:44.695918+00:00. externally triggered: True>: 0 task(s)
[2024-10-15T23:18:12.539+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
